version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/demo_project
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db/mydemoproject"
      REDIS_URL: "redis://redis:6379/1"
      SECRET_KEY: "your_secret_key"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydemoproject
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    # image: redis:6
    ports:
      - "6379:6379"

